### ISSUE TITLE
Grocy changed min PHP version to 7.4

### ISSUE THREAD

**Issue by Forceu** [linuxserver/docker-grocy#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

Grocy changed their composer PHP requirement to 7.4, starting with the next release (https://github.com/grocy/grocy/commit/f1efd08bc692968856c0446f27cc9284c0200579). Right now the PHP version for this docker image is 7.3.
7.4 is technically not required, the author did this, as he is testing with 7.4, but it might change in the future.

These are the options:

- Updating to PHP 7.4
- Replacing the 7.4 requirement with sed, which would be (currently) safe to do
- Only downloading the release file and not running composer

**Comment by j0nnymoe** [comment]
This will be done once alpine 3.13 is released and we've done our usual test/migration process with it.

**Comment by nibblerrick** [comment]
The build of tag/release 3.0.1 seems to [fail](https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-grocy/detail/master/265/pipeline) because of the php-version now so the actual release of the container isn't compatible with @Forceu's latest version of [barcodebuddy](https://github.com/Forceu/barcodebuddy/releases/tag/v1.6.5.1).
If I understand [this](https://gitlab.alpinelinux.org/alpine/aports/-/milestones/149) correct Alpine 3.13 has (had) a milestonedate of 1/1/21 but is not close to be released.
So question is, is there anything that can make this container possible with grocy >= 3.0.1 now?

**Comment by Forceu** [comment]
@nibblerrick in the meantime you can still use the image with the tag v1.6.5.0 to use a version compatible with Grocy 3.0.0 

As far as I am aware @berrnd made the decision to move to 7.4 because it is only tested with that. A dirty fix for this problem would be to modify the version requirement during the build, I will create a PR for that. I am running the new version with 7.3 without any problems and I don't think that there is an actual requirement for 7.4

**Comment by berrnd** [comment]
Yes, it was just about that I cannot test old(er) runtime stuff all the time, it was more about problems when using really old SQLite versions, but PHP older than 7.2 definitely doesn't work.

> https://github.com/grocy/grocy#how-to-install
> - Based on user reports, the minmimum required/**working runtime is PHP 7.2 with SQLite 3.9.0**
>    - However, I don't really care about supporting old runtime stuff, currently everything is only tested against (means 100 % works with) **PHP 7.4 with SQLite 3.27.2**

PHP 7.4 was released over a year ago, the mentioned SQLite version is nearly two years old - so I think this is fine (I'm not requiring bleeding edge versions) and really don't see why this should be a problem...

**Comment by Forceu** [comment]
> the minmimum required/working runtime is PHP 7.2 with SQLite 3.9.0
With the change in the composer.json file Grocy 3.0.1 does not run on any version older than 7.4. Should I open an issue for that on the Grocy page?

**Comment by berrnd** [comment]
No, I will not change that, as it would mean I have to test every change again with PHP 7.2 to fulfill that.

If someone wants to run it with PHP 7.2 and it works, why not, however, it can break with any future commit.

I still don't get why it's so hard to use PHP 7.4 (newer is most of the time better/faster/less resources/...).
(If it's hard here, maybe that's why I personally never started using Docker for anything I run myself...)

**Comment by Roxedus** [comment]
It is not hard, 7.4 is considered unstable for the the version of the OS we use in the container(which is the latest version as the time if writing)

**Comment by Roxedus** [comment]
Next push runs php 7.4
